# Generated by Django 3.0.8 on 2021-02-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='product_image/')),
                ('feature_image', models.ImageField(upload_to='product_image/')),
                ('other_details', models.TextField()),
                ('number_of_people', models.IntegerField()),
                ('price', models.IntegerField()),
                ('guide', models.BooleanField(default=True)),
            ],
        ),
    ]
