# Generated by Django 3.0.8 on 2021-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products_detail',
            name='feature_image',
            field=models.ImageField(upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='products_detail',
            name='image',
            field=models.ImageField(upload_to='product_image'),
        ),
    ]
