# Generated by Django 3.0.8 on 2021-02-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0002_auto_20210210_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ads_on',
            new_name='Add_Feature',
        ),
        migrations.RenameModel(
            old_name='products_detail',
            new_name='Destination',
        ),
    ]
