# Generated by Django 3.0.8 on 2021-02-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0003_auto_20210210_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='your_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products_Details.Add_Feature'),
        ),
    ]
