# Generated by Django 3.0.8 on 2021-02-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0004_destination_your_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='your_choice',
            new_name='additional_feature',
        ),
    ]
