# Generated by Django 3.0.8 on 2021-02-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0005_auto_20210210_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='additional_feature',
        ),
        migrations.AddField(
            model_name='destination',
            name='additional_feature',
            field=models.ManyToManyField(blank=True, null=True, to='Products_Details.Add_Feature'),
        ),
    ]
