# Generated by Django 3.0.8 on 2021-02-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_Details', '0006_auto_20210210_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
